### ISSUE TITLE
Include sample Container.py in docs

### ISSUE THREAD

**Issue by hexDoor** [shubham1172/unshare#5]
Hi,

Would it be possible to get the `Container.py` script referenced in the README onto the repo so that it will be a little bit easier to understand how one can utilise this library?

For context:
I'm working on a thesis where I am trying to create rootless containers in python to execute student submitted code and collect output/side effects for assessment purposes. Your `Container.py` code may help fill in some gaps i've been having when working with `CLONE_NEWPID` and PID 1.  (unless `/bin/bash` is running as PID 1)

Thanks

**Comment by shubham1172** [comment]
Hello @hexDoor, this is the script from the screenshot https://gist.github.com/shubham1172/7c53130e6e0258f998f331955564dc4c

This contains a slightly mature version https://github.com/shubham1172/pocket

**Comment by hexDoor** [comment]
Thanks for the quick response.

This is exactly what I needed to get me past my blocker :)
(will need some tweaking for additional isolation and requirements but will leave a cite in my thesis)

Maybe worth placing the links in `README`?

**Comment by shubham1172** [comment]
Thanks @hexDoor, that's a good idea, added!
